- hosts: all
  become: yes
  vars_files:
     - users_list.yml
     - secret.yml
  tasks:
      - user:
          name: "{{item.username}}"
          password: "{{user_password | string | password_hash('sha512')}}"
          state: present
          group: wheel
          shell: /bin/bash
        with_items: "{{users}}"
        when:
           - "item.uid|string|first == '1'"
           - ansible_nodename in groups['webservers']

      - authorized_key:
          user: "{{item.username}}"
          state: present
          key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        with_items: "{{users}}"
        when:
           - "item.uid|string|first == '1'"
           - ansible_nodename in groups['webservers']

      - user:
          name: "{{item.username}}"
          password: "{{user_password | string | password_hash('sha512')}}"
          state: present
          group: wheel
          shell: /bin/bash
        with_items: "{{users}}"
        when:
         - "item.uid|string|first == '2'"
         - ansible_nodename in groups['database']

      - authorized_key:
          user: "{{item.username}}"
          state: present
          key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        with_items: "{{users}}"
        when:
         - "item.uid|string|first == '2'"
         - ansible_nodename in groups['database']
